spring:
  application:
    name: Greet_Api

  
  boot:
    admin:
      client:
        url: http://localhost:8081/
        
        
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:
  port: 9091