msg: welcome back baby
spring:
  application:
    name: Welcome-Api
  boot:
    admin:
      client:
        url: http://localhost:8081/
        
        
        
management:
  endpoints:
    web:
      exposure:
        include: '*'

